import localFont from "next/font/local";
import {Montserrat} from 'next/font/google'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Mont = Montserrat({
  style: ['normal', 'italic'],
  subsets : ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Mont} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
